### ISSUE TITLE
What is impact_for_meme.sbf?

### ISSUE THREAD

**Issue by vpai** [calganaygun/meme-generator-serverless#1]
Hi there! Cool project. I was trying to implement something similar and was wondering, what is the file `impact_for_meme.sbf` in the fonts folder?

**Comment by calganaygun** [comment]
Hi @vpai! It is font file for the [Impact](https://en.wikipedia.org/wiki/Impact_(typeface)) font family. SBF stands for Symbol Font File. Probably it is not used for my Jimp implementation but I just kept it for future changes. In the same directory FNT file also stands for another font format of the Impact. It is used in Jimp for font settings.
